<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\QQChatLocalReader.Application\QQChatLocalReader.Application.csproj" />
    <ProjectReference Include="..\QQChatLocalReader.Core\QQChatLocalReader.Core.csproj" />
    <ProjectReference Include="..\QQChatLocalReader.Infrastructure\QQChatLocalReader.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>qq-chat-local-reader</AssemblyName>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <Version>0.1.0</Version>
  </PropertyGroup>

</Project>
